---
- name: "create backend dir"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "execute node with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: "print mesage"
  debug:
    msg: "{{execute_node.stdout_lines }}"

- name: "configure pm2 to start "
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu